name: EFFECTIV
favicon: null
layout_spectrum: 0.6811456249561161
typography_spectrum: 0.6551235213410109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.21320172352716327
  lightness: 0.9095417761709541
  saturation: 0.9128233334049582
  rhythmicContrast: 0.054094076389446855
purpose: []
