name: EFFECTIV
favicon: null
layout_spectrum: 0.6811456249561161
typography_spectrum: 0.23984
title: EFFECTIV - Building Dreams Online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2885230-49
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414042'
    - '#afa35f'
    - '#767b7e'
    - '#000000'
    - '#242424'
  brandStrength: 0.21320172352716327
  lightness: 0.9095417761709541
  saturation: 0.9128233334049582
  rhythmicContrast: 0.054094076389446855
purpose: []
